services:
  caddy:
    ports:
      - 80:80
      - 443:443
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile.dev", "--adapter", "caddyfile"]
  
  web:
    build:
      args:
        - DEV=1
    volumes:
      - ./apps/web:/app
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
  
  api:
    volumes:
      - ./apps/api:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${API_PORT}", "--reload"]
  
  ml:
    volumes:
      - ./apps/ml:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${ML_PORT}", "--reload"]